--cria schema
CREATE SCHEMA dbo;

--deleta schema
Drop SCHEMA dbo;

--cria tabela
CREATE TABLE IF NOT EXISTS dbo.cidade (
    ID int generated ALWAYS as identity, --or generated by default as identity
  	nome VARCHAR(150) NOT NUlL,
  	estado CHAR(2) NOT NULL,
  	CONSTRAINT cidade_pk PRIMARY KEY (ID),
  	CONSTRAINT nome_estado_unique UNIQUE (nome, estado)
);
   
   
drop table dbo.cidade;

ALTER TABLE dbo.cidade