-- criando o esquema dbo
CREATE SCHEMA dbo;

SELECT OCTET_LENGTH('ifrn-campus-natal-central'::varchar(10));

-- apagando o esquema dbo
-- DROP SCHEMA dbo;

-- criando a tabela 'cidade'
CREATE TABLE IF NOT EXISTS dbo.cidade (
    ID int generated ALWAYS as identity, --or generated by default as identity
  	nome VARCHAR(150) NOT NUlL,
  	estado CHAR(2) NOT NULL,
  	CONSTRAINT cidade_pk PRIMARY KEY (ID),
  	CONSTRAINT nome_estado_unique UNIQUE (nome, estado)
);

--- apagando a tabela cidade
-- DROP TABLE dbo.cidade;
--- deleda a tabela cidade
-- DELETE TABLE dbo.cidade;

CREATE TABLE IF NOT EXISTS dbo.localizacao(
	latitude FLOAT NOT NULL,
  	longetude FLOAT NOT NULL,
  	id_cidade int NOT NULL,
  	CONSTRAINT localizacao_pk PRIMARY KEY(latitude, longetude),
  	CONSTRAINT cidade_fk FOREIGN KEY(id_cidade) REFERENCES dbo.cidade(ID),
  	CONSTRAINT localizacao_un UNIQUE (id_cidade)
);

CREATE TABLE IF NOT EXISTS dbo.tempo(
  	id INT GENERATED ALWAYS AS IDENTITY,
  	tempo_min INT NOT NULL,
  	tempo_max INT NOT NULL,
  	precip_ploviom REAL NOT NULL,
  	dh_coleta TIMESTAMP NOT NULL,
  	id_cidade INT NOT NULL,
  	CONSTRAINT tempo_pk PRIMARY KEY(ID),
  	CONSTRAINT cidade_fk FOREIGN KEY(id_cidade) REFERENCES dbo.cidade(ID),
  	CONSTRAINT coleta_cidade_un UNIQUE (dh_coleta, id_cidade)
);

CREATE TABLE IF NOT EXISTS dbo.central(
	codigo CHAR(5) NOT NULL,
  	CONSTRAINT central_pk PRIMARY KEY (codigo)
);

CREATE TABLE dbo.tempocentral(
  id_tempo INT NOT NULL,
  codigo_central CHAR(5) NOT NULL,
  CONSTRAINT tempocentral_pk PRIMARY KEY (id_tempo, codigo_central),
  CONSTRAINT tempo_fk FOREIGN KEY (id_tempo) REFERENCES dbo.tempo(id),
  CONSTRAINT central_fk FOREIGN KEY (codigo_central) REFERENCES dbo.central(codigo)
);


--exebir conteudo da tapela
SELECT * FROM dbo.cidade;

--inserindo cidade
INSERT INTO dbo.cidade (nome, estado) VALUES ('NatalRN'); --precisa especivicar os valores (já que o id é gerado automaticamento)
INSERT INTO dbo.cidade (nome, estado) VALUES ('Parnamirim', 'RN');
INSERT INTO dbo.cidade (estado, nome) VALUES ('RN', 'Macaiba');
INSERT INTO dbo.cidade (nome, estado) VALUES ('Parnamirim', 'CE'), ('Recife', 'PE'), ('Fortaleza', 'CE');
--INSERT INTO dbo.cidade VALUES ('Parnamirim', 'RN'); --exemplo de erro

--updadedbo.central
UPDATE dbo.cidade
	SET nome = 'Recife'
    WHERE nome = 'Reife'


--exebir conteudo da tapela
SELECT * FROM dbo.localizacao;

--inserindo localizacao
INSERT INTO dbo.localizacao (latitude, longetude, id_cidade) VALUES (-5.234, 5.234, 1);
INSERT INTO dbo.localizacao (latitude, longetude, id_cidade) VALUES (1.234, -4.56, 2), (5.89, -1.23, 3), (-4.234, 4.234, 4), ('-4.235', 4.234, 5);


--exebir conteudo da tapela
SELECT * FROM dbo.localizacao;


--exebir apenas conteudo diferente, não mosta conteudo repetidos
--SELECT DISTINCT .... 

--conta a quantiade de registros
--SELECT COUNT(*) .... 


--inserindo dados mulos devem ser escrevendo null sem aspas ''

--exemplo de delete
--DELETE FROM dbo.Cliente WHERE email IS NULL;

CREATE TABLE dbo.cliente(
  cpf VARCHAR(
  nome VARCHAR(
  emial VARBINARY(
